import { Component, OnInit } from '@angular/core';
import { OctoFormModel } from 'src/app/@Octo/form/models/octo-form.model';
import { OctoFormUtilsService } from 'src/app/@Octo/form/octo-form-utils.service';
import { ApplicationConfigService } from 'src/app/core/services/application-config.service';

const APPCONFIG_FORM2: OctoFormModel = {
  mode: 'full',
  id: '1',
  title: '',
  class: '',
  style: '',
  sections: [
    {
      id: '1',
      name: 'Section 1',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'textField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Text field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        },
        {
          id: '2',
          name: 'numberField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Number Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'number',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        },
        {
          id: '3',
          name: 'textareaField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Textarea Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'textarea',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        },
        {
          id: '4',
          name: 'checkboxField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'simple',
          label: 'Checkbox Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          value: '',
          type: 'checkbox',
          validation: {
            required: true,
          },
          sectionId: '1',
        },
        {
          id: '5',
          name: 'autocompleteField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Autocomplete Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'autocomplete',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        },
        {
          id: '6',
          name: 'toogleField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Toggle Field',
          labelColor: '',
          borderColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'toggle',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        },
        {
          id: '7',
          name: 'selectField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Select field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'select',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        },
        {
          id: '8',
          name: 'passwordField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Password field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'password',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        },
      ],
    },
    {
      id: '2',
      name: 'Section 2',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'textField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Text field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '2',
          name: 'numberField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Number Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'number',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '3',
          name: 'textareaField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Textarea Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'textarea',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '4',
          name: 'checkboxField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Checkbox Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'checkbox',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '5',
          name: 'autocompleteField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Autocomplete Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'autocomplete',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '6',
          name: 'toogleField',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Toogle Field',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'toggle',
          options: [
            { value: 'File', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '2',
        },
      ],
    },
  ],
};


const APPCONFIG_FORM: OctoFormModel = {
  mode: 'full',
  id: '1',
  title: 'App config form',
  class: '',
  style: '',
  sections: [
    {
      id: '1',
      name: 'startup',
      title: 'Start up from',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'startup',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Startup',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'select',
          options: [
            { value: 'file', label: 'File' },
            { value: 'API', label: 'API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '1',
        }
      ]
    },
    {
      id: '2',
      name: 'customerInfo',
      title: 'Customer info',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'name',
          disabled: false,
          readonly: false,
          placeholder: 'Ex Euronovate, Siga98...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Name',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '2',
          name: 'address',
          disabled: false,
          readonly: false,
          placeholder: 'Ex via roma 1',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Address',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '3',
          name: 'supportEmail',
          disabled: false,
          readonly: false,
          placeholder: 'Ex support@treeocto.com',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Support Email',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '2',
        },
        {
          id: '4',
          name: 'phone',
          disabled: false,
          readonly: false,
          placeholder: 'Ex +3472941411',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Phone',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '2',
        },
      ],
    },
    {
      id: '3',
      name: 'network',
      title: 'Network',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'host',
          disabled: false,
          readonly: false,
          placeholder: '',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Host',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'autocomplete',
          options: [
            { value: 'https://dev.tap-id.tech', label: 'Dev' },
            { value: 'https://test.tap-id.tech', label: 'Test' },
          ],
          validation: {
            required: true,
          },
          sectionId: '3',
        },
        {
          id: '2',
          name: 'basePath',
          disabled: false,
          readonly: false,
          placeholder: 'Ex /euronovate/, /siga98/ ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Base path',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '3',
        },
        {
          id: '3',
          name: 'hostApi',
          disabled: false,
          readonly: false,
          placeholder: '',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Host API',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'autocomplete',
          options: [
            { value: 'https://dev.tap-id.tech', label: 'Dev API' },
            { value: 'https://test.tap-id.tech', label: 'Test API' },
          ],
          validation: {
            required: true,
          },
          sectionId: '3',
        },
        {
          id: '4',
          name: 'hostApiV1',
          disabled: false,
          readonly: false,
          placeholder: '',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Host API V1',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'autocomplete',
          options: [
            { value: 'https://dev.tap-id.tech/v1', label: 'Dev API V1' },
            { value: 'https://test.tap-id.tech/v1', label: 'Test API V1' },
          ],
          validation: {
            required: true,
          },
          sectionId: '3',
        },
        {
          id: '5',
          name: 'hostApiV2',
          disabled: false,
          readonly: false,
          placeholder: '',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Host API V2',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'autocomplete',
          options: [
            { value: 'https://dev.tap-id.tech/v2', label: 'Dev API V2' },
            { value: 'https://test.tap-id.tech/v2', label: 'Test API V2' },
          ],
          validation: {
            required: true,
          },
          sectionId: '3',
        },
        {
          id: '6',
          name: 'hostApiV3',
          disabled: false,
          readonly: false,
          placeholder: '',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Host API V3',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'autocomplete',
          options: [
            { value: 'https://dev.tap-id.tech/v3', label: 'Dev API V3' },
            { value: 'https://test.tap-id.tech/v3', label: 'Test API V3' },
          ],
          validation: {
            required: true,
          },
          sectionId: '3',
        },
        {
          id: '7',
          name: 'openViduServerUrl',
          disabled: false,
          readonly: false,
          placeholder: '',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'OpenVidu server url',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: 'https://rtc.tap-id.tech:4443',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '3',
        },
      ],
    },
    {
      id: '4',
      name: '',
      title: 'Authentication',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'enableAuthentication',
          disabled: false,
          readonly: false,
          placeholder: 'File, API ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Enable authentication',
          labelColor: '',
          borderColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'toggle',
          validation: {
            required: true,
          },
          sectionId: '4',
        },
        {
          id: '2',
          name: 'authenticationMode',
          disabled: false,
          readonly: false,
          placeholder: 'JWT or Cookie',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Authentication mode',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'select',
          options: [
            { value: 'JWT', label: 'JWT' },
            { value: 'Cookie', label: 'Cookie' },
          ],
          validation: {
            required: true,
          },
          sectionId: '4',
        }
      ]
    },
    {
      id: '5',
      name: 'idleConfig',
      title: 'Idle Config',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'timeout',
          disabled: false,
          readonly: false,
          placeholder: 'Ex 1000',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Timeout',
          labelColor: '',
          borderColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'number',
          validation: {
            required: true,
          },
          sectionId: '5',
        },
        {
          id: '2',
          name: 'idle',
          disabled: false,
          readonly: false,
          placeholder: 'Ex 1000',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Idle',
          labelColor: '',
          borderColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'number',
          validation: {
            required: true,
          },
          sectionId: '5',
        },
        {
          id: '3',
          name: 'ping',
          disabled: false,
          readonly: false,
          placeholder: 'Ex 1000',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Ping',
          labelColor: '',
          borderColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'number',
          validation: {
            required: true,
          },
          sectionId: '5',
        },
      ]
    },
    {
      id: '6',
      name: '',
      title: 'Default layout',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'defaultLayout',
          disabled: false,
          readonly: false,
          placeholder: 'Ex /landingpage',
          placeholderColor: '',
          appearance: 'unstyled',
          label: '',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '6',
        }
      ]
    },
    {
      id: '7',
      name: '',
      title: 'Layouts',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'layouts',
          disabled: false,
          readonly: false,
          placeholder: 'Ex /landingpage',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Layouts',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '7',
        }
      ]
    },
    {
      id: '8',
      name: '',
      title: 'Default language',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'layouts',
          disabled: false,
          readonly: false,
          placeholder: 'Ex en, it ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: '',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '8',
        }
      ]
    },
    {
      id: '9',
      name: 'theme',
      title: 'Theme',
      class: 'border-2 broder-grey-100 rounded-md p-4',
      style: '',
      validation: {
        required: true,
      },
      fields: [
        {
          id: '1',
          name: 'favicon',
          disabled: false,
          readonly: false,
          placeholder: 'Ex en, it ...',
          placeholderColor: '',
          appearance: 'unstyled',
          label: 'Favicon',
          labelColor: '',
          borderColor: '',
          textColor: '',
          backgroundColor: '',
          clearable: true,
          value: '',
          type: 'text',
          validation: {
            required: true,
          },
          sectionId: '9',
        }
      ]
    },
  ],
};

@Component({
  selector: 'octo-app-config-form',
  templateUrl: './app-config-form.component.html',
  styleUrls: ['./app-config-form.component.scss'],
  providers: [OctoFormUtilsService],
})
export class AppConfigFormComponent implements OnInit {

  appConfigForm: OctoFormModel = APPCONFIG_FORM;
  constructor(public appService: ApplicationConfigService,) { }

  ngOnInit(): void { }

  formSubmit(form: OctoFormModel) {
    // const sections = this.octoFormUtilsService.getSectionFormMap(form);
    console.log('form submit', form);
  }

  formChange(form: OctoFormModel) {
    console.log('form change', form);
  }
}
